#include <string>

std::string killSounds[33] {
  "bottomfeeder.ogg",
  "godlike.ogg",
  "holyshit_2.ogg",
  "megakill.ogg",
  "ultrakill_2.ogg",
  "combowhore.ogg",
  "godlike_2.ogg",
  "monsterkill.ogg",
  "unstoppable.ogg",
  "dominating.ogg",
  "hattrick.ogg",
  "monsterkill_2.ogg",
  "rampage.ogg",
  "unstoppable_2.ogg",
  "dominating_2.ogg",
  "headhunter.ogg",
  "impressive.ogg",
  "multikill.ogg",
  "rampage_2.ogg",
  "wickedsick.ogg",
  "doublekill.ogg",
  "headshot.ogg",
  "killingspree.ogg",
  "multikill_2.ogg",
  "teamkiller.ogg",
  "wickedsick_2.ogg",
  "headshot_2.ogg",
  "killingspree_2.ogg",
  "perfect.ogg",
  "triplekill.ogg",
  "holyshit.ogg",
  "ludicrouskill.ogg",
  "ultrakill.ogg",
};
